name: semi-hardcore
main: com.ollethunberg.semihardcore.Plugin
version: 0.0.1
api-version: 1.19
authors: [OlleThunberg]
commands:
  semihardcore:
    description: Semi-hardcore main command
    usage: /<command> <action>
    aliases: [semihardcore, sh, shc]
  deaths:
    description: See how many deaths you have.
    usage: /<command>
    aliases: [deaths]
